#!/bin/sh
#
#       Copyright (c) 2002, Valve LLC. All rights reserved.
#
#	a wrapper script for the main hl dedicated server binary
#	Performs auto-restarting of the server on crash. You can
#	extend this to log crashes and more.
#

HL=./hlds
TIMEOUT=10 # time to wait after a crash (in seconds)

# setup the libraries, local dir first!

export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
export LD_PRELOAD="nowon.so"
RESTART=`echo $* | grep "\-restart"` 

if test -n "$RESTART" ; then
	echo "Auto-restarting the server on crash"

	#loop forever
	while true
	do

		# run the server :) the $* passes all the arguments provided to the script 
		#  to the server binary
		$HL $*

		echo "`date`: Server Died"
		sleep $TIMEOUT # don't thrash the hard disk if the server dies, wait a little

	done # while true 
else
	$HL $*
fi
